---

- name: restart sshd
  ansible.builtin.service:
      name: sshd
      state: restarted
      enabled: true

- name: restart snmpd
  ansible.builtin.service:
      name: snmpd
      state: restarted
      enabled: true

- name: confirm grub2 user cfg
  ansible.builtin.stat:
      path: /boot/grub2/user.cfg
  register: rhel7stig_grub2_user_cfg
  notify: make grub2 config

- name: make grub2 config
  ansible.builtin.shell: /usr/sbin/grub2-mkconfig --output={{ rhel7stig_bootloader_path }}grub.cfg
  when:
      - (rhel7stig_grub2_user_cfg is defined) and (rhel7stig_grub2_user_cfg.stat.exists)

- name: copy grub2 config to BIOS/UEFI to satisfy benchmark
  listen: make grub2 config
  ansible.builtin.copy:
      src: "{{ rhel7stig_bootloader_path }}/{{ item }}"
      dest: "{{ rhel7stig_not_boot_path }}/{{ item }}"
      remote_src: true
      mode: 0600
  with_items:
      - grub.cfg
      - user.cfg
  when:
      - (rhel7stig_grub2_user_cfg is defined) and (rhel7stig_grub2_user_cfg.stat.exists)

- name: "restart {{ rhel7stig_time_service }}"
  ansible.builtin.service:
      name: "{{ rhel7stig_time_service }}"
      state: restarted

- name: restart auditd
  ansible.builtin.shell: /usr/sbin/service auditd restart

- name: rebuild initramfs
  ansible.builtin.shell: dracut -f

- name: init aide and wait
  ansible.builtin.shell: /usr/sbin/aide --init -B 'database_out=file:{{ rhel7stig_aide_temp_db_file }}'
  notify: move aide db

- name: init aide
  ansible.builtin.shell: nohup /usr/sbin/aide --init -B 'database_out=file:{{ rhel7stig_aide_temp_db_file }}' > /dev/null &
  notify: move aide db

- name: move aide db
  ansible.builtin.shell: "mv {{ rhel7stig_aide_temp_db_file }} {{ rhel7stig_aide_db_file }}"
  when: not rhel7stig_aide_db_status.stat.exists or rhel7stig_overwrite_aide_db

- name: "Start and Enable SSM Agent"
  ansible.builtin.service:
    name: amazon-ssm-agent
    state: restarted
    enabled: true