---
rhel7stig_min_ansible_version: 2.10.1

# this allows us to insert a name=value into a line of the format:
# key="name1=value1 name2=value2 nameN=valueN"
rhel7stig_regexp_quoted_params: ^({{ rhel7stig_re_qp_key }})({{ rhel7stig_re_qp_other_params }})({{
        rhel7stig_re_qp_param }}?)({{ rhel7stig_re_qp_other_params }})({{ rhel7stig_re_qp_key_end }})
rhel7stig_replace_quoted_params: \1\2{{ rhel7stig_re_qp_insert | ternary('', ' ') }}{{ param }}={{
        value }}{{ rhel7stig_re_qp_insert | ternary(' ', '') }}\4\5

# none of these regexes create capture groups
rhel7stig_re_qp_key: (?:\s*{{ key }}=")
rhel7stig_re_qp_param: (?:{{ rhel7stig_re_qp_insert | ternary('', ' ?') }}{{
        rhel7stig_re_qp_param_start }}{{ param }}=.*?{{
        rhel7stig_re_qp_param_end }}{{ rhel7stig_re_qp_insert | ternary(' ?', '') }})
rhel7stig_re_qp_other_params: (?:(?!{{ rhel7stig_re_qp_param }}.*).)*{{
        rhel7stig_re_qp_insert | ternary('?', '') }}
rhel7stig_re_qp_param_start: (?<=[" ])
rhel7stig_re_qp_param_end: (?=[" ])
rhel7stig_re_qp_key_end: (?:" *)

# insert the parameter at the beginning or append to the end, default append
rhel7stig_re_qp_insert: "{{ insert | default(not (append | default(true))) }}"

extra_path: /usr/local/bin
ansible_remote_tmp: /tmp

lv_list:
  - lv: home_vol
    lv_dev: /dev/vg-01/home_vol
    size: 5G
    mount_point: /home
    mount_options: nodev
    selinux_context: user_home_dir_t
  - lv: var_vol
    lv_dev: /dev/vg-01/var_vol
    size: 10G
    mount_point: /var
    mount_options: defaults
    selinux_context: var_t
  - lv: var_log_vol
    lv_dev: /dev/vg-01/var_log_vol
    size: 10G
    mount_point: /var/log
    mount_options: defaults
    selinux_context: var_log_t
  - lv: var_log_audit_vol
    lv_dev: /dev/vg-01/var_log_audit_vol
    size: 5G
    mount_point: /var/log/audit
    mount_options: defaults
    selinux_context: auditd_log_t
  - lv: var_tmp_vol
    lv_dev: /dev/vg-01/var_tmp_vol
    size: 9G
    mount_point: /var/tmp
    mount_options: nodev,nosuid,noexec
    selinux_context: tmp_t

gpg_keys:
  - name: 'release key 2'
    packager: 'security@redhat.com'
    fingerprint: '567E 347A D004 4ADE 55BA  8A5F 199E 2F91 FD43 1D51'

  - name: 'auxiliary key'
    packager: 'security@redhat.com'
    fingerprint: '43A6 E49C 4A38 F4BE 9ABF  2A53 4568 9C88 2FA6 58E0'

gpg_package: "redhat-release"
rpm_gpg_key: /etc/pki/rpm-gpg/RPM-GPG-KEY-{{ ansible_distribution | lower }}-release

# RHEL-07-032000
# mcafee_agent_bucket: oea-administration
# mcafee_agent_object: HBSS/20240131_LinuxHBSS_581313/install.sh
mcafee_agent_path: /tmp/mcafee_install.sh

# RHEL-07-010240 | RHEL-07-010260
# user_accounts:
#   - ec2-user
#   - ssm-user

# RHEL-07-010240 | RHEL-07-010260 | RHEL-07-010340
user_accounts:
  - name: ec2-user
    description: "ec2-user password"
  - name: ssm-user
    description: "ssm-user password"
  - name: root
    description: "root password"
user_passwords: {}
#  RHEL-07-010340
kms_key_id: "8a79dbf4-2d3c-4753-bb1e-3e443f1379ac"  # Update