---

- name: Find EBS volume device name of first device that is not partitioned
  set_fact:
    block_device_name: "{{ ansible_devices | dict2items | selectattr('value.partitions', 'equalto', {}) | map(attribute='key') | first }}"

- name: Output block device name
  debug:
    var: block_device_name
  when: block_device_name is defined
