---

- name: Install LVM2
  ansible.builtin.yum:
    name: lvm2
    state: present

- name: rsync the data to /tmp
  ansible.builtin.shell: rsync -av {{ item.mount_point }}/ /tmp{{ item.mount_point }}/
  loop: "{{ lv_list }}"

- name: Create volume group
  community.general.lvg:
    vg: vg-01
    pvs: "{{ block_device_name }}"

- name: Create logical volumes
  community.general.lvol:
    vg: vg-01
    lv: "{{ item.lv}}"
    size: "{{ item.size }}"
  loop: "{{ lv_list }}"

- name: Format the xfs filesystem
  community.general.filesystem:
    fstype: xfs
    dev: "{{ item.lv_dev }}"
  loop: "{{ lv_list }}"  

- name: Get UUIDs of logical volumes
  shell: blkid -s UUID -o value "{{ item.lv_dev }}"
  register: lv_uuid
  loop: "{{ lv_list }}"
  changed_when: false

- name: Mount Logical Volumes
  ansible.posix.mount:
    path: "{{ item.mount_point }}"
    src: "UUID={{ lv_uuid.results | selectattr('item.lv', 'equalto', item.lv) | map(attribute='stdout') | first }}"
    fstype: xfs
    opts: "{{ item.mount_options }}"
    state: mounted
    dump: 0
    passno: 2
  loop: "{{ lv_list }}"

- name: rsync the data to new mounts
  ansible.builtin.shell: rsync -av /tmp{{ item.mount_point }}/ {{ item.mount_point }}/ 
  loop:  "{{ lv_list }}"