---

- name: Check OS version and family
  ansible.builtin.assert:
      that: ansible_os_family == 'RedHat' and ansible_distribution_major_version is version_compare('7', '==')
      msg: "This role can only be run against RHEL/CENTOS 7. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  tags:
      - always

- name: Check ansible version
  ansible.builtin.assert:
      that: ansible_version.full is version_compare(rhel7stig_min_ansible_version, '>=')
      msg: You must use Ansible {{ rhel7stig_min_ansible_version }} or greater
  tags:
      - always

- name: FIPS turned on
  ansible.builtin.set_fact:
      fips_value: '1'
  tags:
      - RHEL-07-021350

- name: Include OS specific variables
  ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"
  tags:
      - always

- name: include prelim tasks
  ansible.builtin.import_tasks:
      file: prelim.yml
  tags:
      - prelim_tasks

- name: Gather the package facts
  ansible.builtin.package_facts:
      manager: auto
  tags:
      - always

- name: Install OLDCC requirements
  ansible.builtin.import_tasks:
      file: oldcc-base.yml
  tags:
      - oldcc-base

- name: Include CAT I patches
  ansible.builtin.import_tasks:
      file: fix-cat1.yml
  tags:
      - high

- name: Include CAT II patches
  ansible.builtin.import_tasks:
      file: fix-cat2.yml
  tags:
      - medium

- name: Include CAT III patches
  ansible.builtin.import_tasks:
      file: fix-cat3.yml
  tags:
      - low

- name: update auditd
  ansible.builtin.template:
      src: audit/99_auditd.rules.j2
      dest: /etc/audit/rules.d/99_auditd.rules
      owner: root
      group: root
      mode: 0600
  register: auditd_file
  notify: restart auditd
  tags:
      - auditd

- name: flush handlers
  ansible.builtin.meta: flush_handlers
