---

- name: Check OS version and family
  ansible.builtin.assert:
      that: ansible_os_family == 'RedHat' and ansible_distribution_major_version is version_compare('7', '==')
      msg: "This role can only be run against RHEL/CENTOS 7. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  tags:
      - always

- name: Check ansible version
  ansible.builtin.assert:
      that: ansible_version.full is version_compare(rhel7stig_min_ansible_version, '>=')
      msg: You must use Ansible {{ rhel7stig_min_ansible_version }} or greater
  tags:
      - always

- name: FIPS turned on
  ansible.builtin.set_fact:
      fips_value: '1'
  tags:
      - RHEL-07-021350

- name: include prelim tasks
  ansible.builtin.import_tasks:
      file: prelim.yml
  tags:
      - prelim_tasks

- name: "Get password lock status of ec2-user"
  block:
    - name: "Password lock status of ec2-user"
      ansible.builtin.command: "grep ec2-user /etc/shadow"
      register: ec2_password_lock_status

    - name: "Output Password lock status of ec2-user"
      ansible.builtin.debug:
        var: ec2_password_lock_status.stdout

- name: Gather the package facts
  ansible.builtin.package_facts:
      manager: auto
  tags:
      - always

- name: Install OLDCC requirements
  ansible.builtin.import_tasks:
      file: oldcc-base.yml
  tags:
      - oldcc-base

- name: "Get password lock status of ec2-user"
  block:
    - name: "Password lock status of ec2-user"
      ansible.builtin.command: "grep ec2-user /etc/shadow"
      register: ec2_password_lock_status

    - name: "Output Password lock status of ec2-user"
      ansible.builtin.debug:
        var: ec2_password_lock_status.stdout

- name: Install additional volumes for separate partitions of /home, /var, /var/log, /var/log/audit, and /var/tmp
  ansible.builtin.import_tasks:
      file: volumes.yml
  tags:
      - volumes

- name: "Get password lock status of ec2-user"
  block:
    - name: "Password lock status of ec2-user"
      ansible.builtin.command: "grep ec2-user /etc/shadow"
      register: ec2_password_lock_status

    - name: "Output Password lock status of ec2-user"
      ansible.builtin.debug:
        var: ec2_password_lock_status.stdout

- name: HIGH Severity
  ansible.builtin.import_tasks:
      file: severity-high.yml
  tags:
      - high

- name: "Get password lock status of ec2-user"
  block:
    - name: "Password lock status of ec2-user"
      ansible.builtin.command: "grep ec2-user /etc/shadow"
      register: ec2_password_lock_status

    - name: "Output Password lock status of ec2-user"
      ansible.builtin.debug:
        var: ec2_password_lock_status.stdout

- name: MEDIUM Severity
  ansible.builtin.import_tasks:
      file: severity-medium.yml
  tags:
      - medium

- name: "Get password lock status of ec2-user"
  block:
    - name: "Password lock status of ec2-user"
      ansible.builtin.command: "grep ec2-user /etc/shadow"
      register: ec2_password_lock_status

    - name: "Output Password lock status of ec2-user"
      ansible.builtin.debug:
        var: ec2_password_lock_status.stdout

- name: LOW Severity
  ansible.builtin.import_tasks:
      file: severity-low.yml
  tags:
      - low

- name: "Get password lock status of ec2-user"
  block:
    - name: "Password lock status of ec2-user"
      ansible.builtin.command: "grep ec2-user /etc/shadow"
      register: ec2_password_lock_status

    - name: "Output Password lock status of ec2-user"
      ansible.builtin.debug:
        var: ec2_password_lock_status.stdout

- name: update auditd
  ansible.builtin.template:
      src: audit/99_auditd.rules.j2
      dest: /etc/audit/rules.d/99_auditd.rules
      owner: root
      group: root
      mode: 0600
  register: auditd_file
  notify: restart auditd
  tags:
      - auditd

- name: "Get password lock status of ec2-user"
  block:
    - name: "Password lock status of ec2-user"
      ansible.builtin.command: "grep ec2-user /etc/shadow"
      register: ec2_password_lock_status

    - name: "Output Password lock status of ec2-user"
      ansible.builtin.debug:
        var: ec2_password_lock_status.stdout

- name: flush handlers
  ansible.builtin.meta: flush_handlers

- name: "Get password lock status of ec2-user"
  block:
    - name: "Password lock status of ec2-user"
      ansible.builtin.command: "grep ec2-user /etc/shadow"
      register: ec2_password_lock_status

    - name: "Output Password lock status of ec2-user"
      ansible.builtin.debug:
        var: ec2_password_lock_status.stdout