---

- name: Install Amazon SSM Agent
  block:
    - name: Download amazon-ssm-agent.rpm
      ansible.builtin.get_url:
        url: https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
        dest: /tmp/amazon-ssm-agent.rpm

    - name: Install amazon-ssm-agent.rpm
      ansible.builtin.package:
        name: /tmp/amazon-ssm-agent.rpm
        disable_gpg_check: true
        state: latest
      notify: "Start and Enable SSM Agent"
  tags: ssm

- name: Install Nano, Unzip, Wget
  ansible.builtin.package:
    name:
      - nano
      - unzip
      - wget
    state: latest
  tags: nano,unzip,wget

- name: Download EPEL repository
  ansible.builtin.get_url:
    url: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    dest: /tmp/epel-release-latest-7.noarch.rpm
  tags: epel

- name: Install EPEL package
  ansible.builtin.package:
    name: /tmp/epel-release-latest-7.noarch.rpm
    disable_gpg_check: true
    state: latest
  tags: epel

- name: Add "{{ extra_path }}" to PATH of root user
  ansible.builtin.lineinfile:
    path: /root/.bashrc
    line: 'export PATH="{{ extra_path }}:$PATH"'
    state: present
  tags: path

- name: Install AWS CLI v2
  block:
    - name: Make /tmp directory executable temporarily
      ansible.posix.mount:
        path: /tmp
        state: remounted
        opts: exec

    - name: Check if awscliv2 is installed.
      ansible.builtin.command: 
        cmd: "/usr/local/bin/aws --version"
      register: awscliv2_installed
      failed_when: false
      changed_when: false

    - name: Download awscliv2 installer.
      ansible.builtin.unarchive: 
        src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp
        remote_src: yes
      when: awscliv2_installed.rc != 0

    - name: Install AWS CLI v2
      ansible.builtin.command: 
        cmd: "/tmp/aws/install"
      when: awscliv2_installed.rc != 0
  tags: awscli

- name: Import DoD root and WCF certificates into linux CA store
  ansible.builtin.script: ./scripts/add-dod-and-wcf-certs.sh
  tags: import_certs

- name: Install AWS certificate bundle for GovCloud regions
  ansible.builtin.get_url:
    url: https://truststore.pki.us-gov-west-1.rds.amazonaws.com/global/global-bundle.pem
    dest: /etc/pki/tls/certs/global-bundle.pem
    mode: '0644'
  tags: import_certs
